[book]
authors = ["subfish-zhou"]
language = "en"
multilingual = false
src = "src"
title = "动手学强化学习"

[build]
build-dir = "out"

[output.html]
mathjax-support = true
git-repository-url = "https://github.com/subfish-zhou/Dive-into-Deep-RL"